
DATABASE_STR = "DATABASE"
DATABASE_IS_CREATED = "DATABASE '{}' IS SUCCESSFULLY CREATED"
DATABASE_IS_DELETED = "DATABASE '{}' IS SUCCESSFULLY DELETED"
TEST_IS_ADDED = "TEST '{}' IS SUCCESSFULLY ADDED TO DATABASE '{}'"
NO_SUCH = "NO SUCH {} {}"
NO_SUCH_INTO = "NO SUCH {} IN {}"